import type { Metadata } from "next";
import "./globals.css";
import "./styles/tokens.css";
// ------------------------------
// LOCAL SWITZER FONT (OFFLINE)
// ------------------------------
import localFont from "next/font/local";
import Header from "../components/Header/Header";

const switzer = localFont({
  src: [
    {
      path: "../../public/fonts/Switzer-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Switzer-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/Switzer-Bold.otf",
      weight: "700",
      style: "normal",
    },
    // OPTIONAL — only if you really need it
    {
      path: "../../public/fonts/Switzer-Extrabold.otf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-switzer",
  display: "swap",
});

export { switzer };

export const metadata: Metadata = {
  title: "Qendrim Caka",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${switzer.variable} min-h-screen bg-white text-black antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
